import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

/**
 * Vite configuration.
 *
 * Notable choices:
 *  - The service worker is generated by `vite-plugin-pwa` (Workbox `generateSW`).
 *  - Only the *application shell* is precached. Every `/api/` request is
 *    explicitly `NetworkOnly`, so authenticated vehicle/owner data is never
 *    written to the Cache Storage of a shared device.
 *  - The SW is disabled in dev so hot reloading is never served from a cache.
 *    Test the PWA with `npm run build && npm run preview`.
 */
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Keep dev free of service-worker caching surprises.
      devOptions: { enabled: false },
      includeAssets: ['favicon.svg', 'icons/apple-touch-icon.png', 'robots.txt'],
      // Keep `name` in step with APP_NAME in src/constants/app.js.
      manifest: {
        name: 'Remind Vahan',
        short_name: 'Remind Vahan',
        description:
          'Track vehicle insurance and PUC expiry dates with simple email reminders.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait-primary',
        theme_color: '#3b2ed4',
        background_color: '#f8fafc',
        lang: 'en-IN',
        categories: ['productivity', 'utilities'],
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: 'icons/maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        // SPA deep links (/vehicles/123, /settings) resolve to the shell.
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//],
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
        // Never let Workbox cache an API response, even opportunistically.
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.startsWith('/api/'),
            handler: 'NetworkOnly',
          },
        ],
      },
    }),
  ],
  server: {
    port: 5173,
    // Matches the backend's default CORS_ALLOWED_ORIGINS / FRONTEND_URL.
    strictPort: false,
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
    rollupOptions: {
      output: {
        // Keep vendor code in its own long-lived chunk.
        manualChunks: {
          react: ['react', 'react-dom', 'react-router-dom'],
        },
      },
    },
  },
});
